#pragma once
#include <iostream>
#include <memory>
#include <vector>
#include <algorithm>
#include <string>
#include <map>
#include <iomanip>
#include <stdexcept>
#include <cmath>
#include <cstring>
#include <QString>
